### ISSUE TITLE
[SonarQube] Add unit test to meet 80% minimum bar.

### ISSUE THREAD

**Issue by ikp4success** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#100]
**Describe the bug**
Add more unit test to meet SonarCube 80% minimum requirement.

**Expected behavior**
- SonarQube should show _**green**_ in report of test coverage.

**Comment by ikp4success** [comment]
- https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/issues/9

**Comment by ikp4success** [comment]
**TODO**: https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/pull/91/commits/cd9e2f97b574be446e25838e8417eb35bb04e4cb

**Comment by andrewmarriott-aws** [comment]
Finished: https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/pull/153
