### ISSUE TITLE
move all tests to source/test/ folder

### ISSUE THREAD

**Issue by ianwow** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#106]
The integration tests have been saved under source/api/tests even though e2e and unit tests are under source/tests. The pattern for solutions is to put unit, integ, and e2e tests all in the same subfolder (e.g. source/tests/unit/, source/tests/integ/, source/test/e2e/). I request that the integ tests be moved to source/tests/integ/ in order to improve the organization of those test assets.

**Comment by ikp4success** [comment]
If you can resolve this issue, then resolve this as well -> https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/issues/107
