### ISSUE TITLE
Turn on S3 bucket versioning

### ISSUE THREAD

**Issue by tomgilman** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#114]
**Is your feature request related to a problem? Please describe.**
Turn on S3 bucket versioning.

**Describe the feature you'd like**
 AWS suggests a better practice is to turn on versioning.

**Comment by alesnarx** [comment]
Marking the associated flagged security issue as "Not Useful" / NA as our S3 buckets do not store customer data, therefore do not need this versioning feature. Marking ticket as closed.
