### ISSUE TITLE
Turn on https for S3 bucket traffic

### ISSUE THREAD

**Issue by tomgilman** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#115]
**Is your feature request related to a problem? Please describe.**
 A best practice is to only allow https traffic to S3 buckets.

**Describe the feature you'd like**
 set the bucket policy to work only with https.

**Comment by alesnarx** [comment]
This was the recommended implementation by Aristotle: https://www.aristotle.a2z.com/implementations/8

We have already implemented `aws:SecureTransport: false` on all 3 S3 buckets in the CloudFormation template following the reference above to ensure HTTPS only for S3 traffic.
