### ISSUE TITLE
Add support for non-US locales

### ISSUE THREAD

**Issue by ianwow** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#12]
Normalization for address, zip, and phone number is currently hardcoded to use 'US' as the country code.
We need to let users enter a country code in Step 3, then pass that to the Glue script so that it can normalize according to the right convention.

Make sure to implement all the normalization rules in [AdsAmcHashingTool](https://code.amazon.com/packages/AdsAmcHashingTool).

**Comment by ianwow** [comment]
Related to https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/issues/30

**Comment by andrewmarriott-aws** [comment]
Tested and verified UK country-code functionality. No code update needed.

Used the following site to generate a list of 10,000 UK-based addresses (addresses are pulled from Google Maps and provide the best means of testing against real data): https://www.doogal.co.uk/RandomAddresses 

Of the 10,000 addresses hashed, 100% matched the hashing solution provided by AMC. 

List of confirmed functional locales as of this comment:
-US
-UK

**Comment by tomgilman** [comment]
Let's include the top 6 markets.

**Comment by andrewmarriott-aws** [comment]
UK support added: https://github.com/orgs/aws-solutions/projects/9/views/5?pane=issue&itemId=19557100

**Comment by andrewmarriott-aws** [comment]
Closing ticket. Opened separate tickets for each locale:
#121 
#122 
#123 
#124 
#125 
#126 
#127 
#128
