### ISSUE TITLE
AMC-I Restructure into AWS Solutions repository format (folders, scripts, etc.)

### ISSUE THREAD

**Issue by cassneal** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#135]
Install skeleton solution layout into a branch, consider merging or other to re-organize.

**Comment by andrewmarriott-aws** [comment]
Issue attached to incorrect repository. Closing and tracking issue here instead: https://github.com/orgs/aws-solutions/projects/9/views/2?filterQuery=AMC-I&pane=issue&itemId=21557142
