### ISSUE TITLE
Duplicate error messages when merging incompatible JSON and CSV

### ISSUE THREAD

**Issue by ianwow** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#149]
**Describe the bug**

There are 3 different error messages when uploading a CSV to an existing JSON data set. Should this be consolidated into 1 message?

![image](https://user-images.githubusercontent.com/54998167/222573599-0a4ea2c7-d7e1-4a9d-874b-ef4657da7305.png)

**Comment by tomgilman** [comment]
fixed
