### ISSUE TITLE
misc directory naming improvements

### ISSUE THREAD

**Issue by ianwow** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#189]
The test directory would be easier to understand if all the files related to unit test lived under `unit/` and all the integration test files lived under `integ/` and all the e2e relates files lived under `e2e/`.

Also, the `source/shared/` directory contains only one package, which is `Sigv4`. Since this directory contains an `__init__.py` file, it is considered a Python package, and therefore does not belong in an ambiguously named `/source/shared/` directory. For more information about file structure best practices, read this:
https://docs.python-guide.org/writing/structure/

Every package should live in its own directory. Sigv4 files should live in `source/sigv4/`. So, I recommend we rename the `shared` directory to `sigv4`.

**Comment by ianwow** [comment]
This issue is related to #186

**Comment by ikp4success** [comment]
~> The test directory would be easier to understand if all the files related to unit test lived under `unit/` and all the integration test files lived under `integ/` and all the e2e relates files lived under `e2e/`.~
> 
> Also, the `source/shared/` directory contains only one package, which is `Sigv4`. Since this directory contains an `__init__.py` file, it is considered a Python package, and therefore does not belong in an ambiguously named `/source/shared/` directory. For more information about file structure best practices, read this: https://docs.python-guide.org/writing/structure/
> 
> Every package should live in its own directory. Sigv4 files should live in `source/sigv4/`. So, I recommend we rename the `shared` directory to `sigv4`.
