### ISSUE TITLE
Root URL leads to page with "Confirm Details" and error "Invalid dataset"

### ISSUE THREAD

**Issue by cgeiaws** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#236]
**Describe the bug**
When logging into the AMC Uploader solution and landing on the root URL (https://{instance}.cloudfront.net/) an error is displayed.  

**To Reproduce**
Steps to reproduce the behavior.

Log in to AMC Uploader
Redirects to / 

**Expected behavior**

Login should drop the user on /step6 perhaps or a page that is not part of the step by step process which requires prior input. 

**Please complete the following information about the solution:**
Version: v2.0.0

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

![Screenshot 2023-04-18 at 14 41 02](https://user-images.githubusercontent.com/93347162/232911614-38d980ad-0162-41e6-bbc6-d5b4ad5b61bd.png)

**Additional context**

**Comment by cassneal** [comment]
@cgeiaws  this will be fixed in 2.1.0 release coming up soon.

**Comment by ianwow** [comment]
This issue was fixed in #238
