### ISSUE TITLE
support uploads to multiple AMC instances

### ISSUE THREAD

**Issue by andrewmarriott-aws** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#24]
Support for multi-AMC instance upload is very important because AMC's biggest users (GSIs, Agencies, etc) need to support uploading to multiple instances. Right now they'd have to deploy a separate AMCUFA stack for each AMC instance. Instead, we should allow them to do this from a single stack.

**Comment by ianwow** [comment]
# Design Proposal 1

We're using CloudFormation parameters to input AMC instance info here. This allows us to bind that state at deploy time. It would be more convenient for users to enter this info via an admin page in the webui, but I this would require us to manage that state in a new Database resource.

1. Add a new CloudFormation parameter for users to input an array of dicts in this format: `[{"AMC_ENDPOINT": "", "AMC_DATA_ACCOUNT_UPLOAD_ID": "", "REGION": ""}, ...]`
2. Pass that dict as an env variable to the API stack and the Web stack
3. Put each AMC_DATA_ACCOUNT_UPLOAD_ID in the ArtifactBucketPolicy to grant each AMC instance read permission
5. Put a multi-select menu in the dataset definition web form for users to specify target AMC instance(s).
6. Put a multi-select menu in the Monitoring web form for users to specify target AMC instance(s).
7. Modify the API stack and the amc_uploader lambda to broadcast /create_dataset to each selected AMC endpoint. 
8. Modify /list_datasets to take AMC endpoint as a new request argument.

**Comment by ianwow** [comment]
# Design Proposal 2

Same as above, except instead of using CF parameters to bind AMC Instance info, use a web form for admin users.

1. Add a new user type to grant access to the admin web form
2. Create a web form for users to register and deregister AMC instances
3. Add new API resources for registering and deregistering AMC instances
4. Add DynamoDB (DDB) resource to keep AMC instance state
5. Add DDB client to API stack and web stack

**Comment by ianwow** [comment]
Because this will involve changes to the APIHandler, we need to add https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/issues/65 as a dependency.

**Comment by ianwow** [comment]
Proposed GUI:
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/54998167/214959905-0c286dfd-ec2e-4f46-8693-3e7d40eddf7c.png">

**Comment by ianwow** [comment]
AMC selection form:

![image](https://user-images.githubusercontent.com/54998167/215612099-85b9280c-b654-4d41-a9d8-a206ff3ba7f1.png)

**Comment by ianwow** [comment]
AMC Instance registration:

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/54998167/215855123-090d1e43-6f0e-4bbf-aa5d-829b1589ee18.png">


Dataset selection for upload:

![image](https://user-images.githubusercontent.com/54998167/215854698-4f879b04-3d69-445e-90cd-4e155c6d0d16.png)

Dataset upload review:

![image](https://user-images.githubusercontent.com/54998167/215855493-5220dd81-0d9c-4dc3-adfb-6efa00280fa2.png)

Dataset selection for upload monitoring:

![image](https://user-images.githubusercontent.com/54998167/215855733-db8f1567-8758-482b-b25a-341d24b307b9.png)

**Comment by ianwow** [comment]
# Register AMC Instances:

![image](https://user-images.githubusercontent.com/54998167/215856266-97ec43a8-0304-4da7-a48b-baaf1aa088f5.png)


# Select AMC Instances for upload:

![image](https://user-images.githubusercontent.com/54998167/215856024-cc109f5b-5eef-476d-8772-5299899a85b9.png)

# Review upload details:

![image](https://user-images.githubusercontent.com/54998167/215856081-efb4683b-e462-4e38-ba33-1ab1e1dc085b.png)

# Select AMC Instance for monitoring uploads

![image](https://user-images.githubusercontent.com/54998167/215855817-91405f4c-dcee-4a6f-8f9e-71ba96b18e94.png)

**Comment by ianwow** [comment]
This feature is complete. However, automated API tests are failing for a variety of reasons. I opted to remove them since we're doing manual API tests anyway. If the team decides that these tests are high priority, then resolve #92 to bring them back in.

**Comment by ianwow** [comment]
This issue has been deprecated by https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/pull/133
