### ISSUE TITLE
Visualize the queryable time ranges for datasets

### ISSUE THREAD

**Issue by andrewmarriott-aws** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#25]
One of the challenges AMC customers have is understanding the time ranges over which they can query for their datasets. We can build a bar graph visualization into 1pd4amc to help customers get more information about data certificates, i.e. where gaps exist, where data is overlapping, when time ranges were uploaded, etc.

**Comment by tomgilman** [comment]
@andrewmarriott-aws can we add more detail here?

**Comment by tomgilman** [comment]
We're not going to proceed with this.
