### ISSUE TITLE
Cognito Federation with Azure

### ISSUE THREAD

**Issue by xiyue-55** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#256]
Hi,

I've recently deployed AMC Uploader and setup the cognito OIDC federation with Azure. But it doesn't seems work properly as I want.
Once I login with Azure, I get redirected to the Uploader login page, and have to enter usename and password.

I've check the web application code. I thought if I want to use Azure to connect to AMC Uploader, the configuration should be in amplify auth.

Could we have this feature  available soon? Otherwise, do you have any other solution or advices on this subject?

Thanks for your response!

**Comment by mikeols** [comment]
Hi @xiyue-55, federating with Azure would be outside the scope of what we can directly support for this solution currently. However, in the 3.0 release coming this spring, we will be switching to the Cognito Hosted UI for authentication, which should be easier for you to use for federating with another identity provider. We will also add this use-case to our backlog and we'll explore if it is something we want to start supporting.
