### ISSUE TITLE
AWS Account linking problem

### ISSUE THREAD

**Issue by xiyue-55** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#260]
Hello,

I recently deployed an AMCUFA.
When I tried to upload data into AMC Instance, I got 401 error.

After checking the AMC Instance settings, the AWS account used to deploed AMCUFA is found different from the **Data upload AWS account ID** in AMC interface.
Should the AMCUFA be deployed in with the same account set in AMC interface? Or should I set the Uploader deployed AWS account as **Connected AWS account ID** in AMC?

For the API endpoint, I found the following in AMC interface: https://advertising-api-eu.amazon.com/amc/reporting/amcxxxxx. This is not the format demanded in AMCUFA. Do you have any idea about it?
![image](https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/assets/163162007/0d206532-2994-436e-87a2-fea3c3a49229)

Thanks for your help!

Xiyue

**Comment by davidbeckonline** [comment]
Hey Xuyue,

in short: The information you see in the UI does not fit to the AMCUFA solution right now, as an API migration is ongoing. My recommendation would be to wait a few more days. The next version of the AMCUFA solution will fix this issue.

BACKGROUND
AMC is migrating to the Ads API. See here:
https://advertising.amazon.com/API/docs/en-us/guides/amazon-marketing-cloud/amc-migration-hub/migration
Until August 2024, there are now two APIs for AMC:
* Ads API (new)
* "legacy instance level API" (old)

The information you see in the AMC UI is already for the new Ads API.
However, the current version of the AMCUFA solution is only supporting the "old" API for AMC.

NEXT STEPS
My recommendation is to wait for the next AMCUFA version, which is said to be released in the near future.
Alternatively, you could reach out to the AMC-support via email and ask them for the right inputs for the "old" API. But I think your time is better invested in setting yourself up for the Ads API (see link above).


Hope that helps.

**Comment by xiyue-55** [comment]
Hi David,

Thanks a lot for your response.

For the question about the AWS account, should I delpoyed AMCUFA in same account set in AMC as "**Data upload AWS account ID**"?

Do you have any idea in how many days will the new version be released?

**Comment by mikeols** [comment]
Hi @xiyue-55 we are planning on releasing the new version (3.0) this afternoon. We can let you know once we release.

**Comment by xiyue-55** [comment]
Hello,

Thanks for the information. Looking forward to the new release!

Actually we have an infra like the following picture shows
![image](https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/assets/163162007/2aac8678-4e51-4550-bfd9-30a62a197ce3)
Should I deployed my AMCUFA in AWS account A or there's another way to authenticate/link AWS account B to my AMC instance which has AWS account A as **"Data upload AWS account ID"**?

Thanks for your help!

**Comment by ianwow** [comment]
@xiyue-55 You can install AMCUFA in either account but it would be easier for you to install it in the same account that owns the source data S3 bucket. If you install AMCUFA in a different account then you'll need to setup an S3 policy on that bucket to enable the other account to list and read your source data files.

AMCUFA v3.0.0 was released today. This release does not require you to deploy in the same account as the "Connected AWS Account", so I'm going to close this ticket. Please open a new ticket if you have further issues. Thanks!
