### ISSUE TITLE
Allow users to upload data to existing datasets

### ISSUE THREAD

**Issue by ikp4success** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#3]
Implementation is finished but waiting until v2 to merge so that we can minimize risk for v1.
See screenshots in the PR.
Code review is TBD.

**Comment by ianwow** [comment]
@alesnarx The following code diff might give you a running start on this task:
https://gitlab.aws.dev/ianwow/1pd4amc/-/merge_requests/31
