### ISSUE TITLE
Allow users to upload gzipped files

### ISSUE THREAD

**Issue by ikp4success** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#5]
Allow users to upload gzipped files. Require users to specify JSON/CSV in Step 2 (i.e. leave the current behavior), but make sure that step doesn't produce an error when it tries to autodetect JSON/CSV.
We'll need to look at the first row of the file in order to get column names for Step 3. That means we'll need to uncompress the file. Can we unzip on-the-fly without any temporary files using S3 Object Lambda?
We don't need to uncompress the entire file. Maybe we can use S3 Object Lambda to stream uncompressed objects to the get-object api, then the lambda function that feeds Step 3 can read the data columns on the first line via that get-object api.

**Comment by ikp4success** [comment]
Here is sample code that shows how to compress s3 objects on-the-fly with s3 object lambda:

https://docs.aws.amazon.com/AmazonS3/latest/userguide/olap-writing-lambda.html#range-get-olap

Maybe we can modify that to uncompress instead of compress.

**Comment by alesnarx** [comment]
Merged and completed.
