### ISSUE TITLE
[SonarQube] Meet the Quality Bar

### ISSUE THREAD

**Issue by tomgilman** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#74]
Big green dot

**Comment by ianwow** [comment]
I propose that we use solution builder feature pipelines to run Sonarqube on this project. I think we can close this issue when:
1. sonarqube checks pass for the development branch, and 
2. sonarqube checks are included in the pr-workflow

**Comment by ikp4success** [comment]
This issue is broken down to mini tasks below:
- https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/pull/91
- Add unit test to meet Sonar Cube 80% minimum bar
- Setup SonarCube pipeline

**Comment by ianwow** [comment]
I setup a pipeline we can use to run sonarqube:
https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/amazon-marketing-cloud-uploader-from-aws-v2_0_0-feature/view?region=us-east-1

**Comment by ikp4success** [comment]
> I setup a pipeline we can use to run sonarqube: https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/amazon-marketing-cloud-uploader-from-aws-v2_0_0-feature/view?region=us-east-1 You can trigger it by pushing commits to the `github_first` branch.

Is this going to be the process, for every PR, to merge to `github_first`?

**Comment by ianwow** [comment]
We were asked to avoid merging any PR that contains unresolved sonarqube issues. If the solution builder pipelines are the only way we can run sonarqube, then we'll need to create a new pipeline for every PR. So, we can either do that, or figure out how to run sonarqube from a github action.

**Comment by ikp4success** [comment]
![image](https://user-images.githubusercontent.com/7339334/224126459-dfa38b71-28b3-4178-970a-f0c32c502abb.png)
