### ISSUE TITLE
Update build_dir in build-s3-dist.sh

### ISSUE THREAD

**Issue by davidbeckonline** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#84]
**Description**
The current definition of `build_dir` in the `build-s3-dist.sh` needs to be updated to 
~~~~
build_dir="$PWD/deployment/"
~~~~ 

**Steps to reproduce**
Follow the advanced installation steps given in
[build_dir="$PWD/deployment"](https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws#building-the-solution-from-source-code)

Step 
~~~~
./build-s3-dist.sh --template-bucket ${TEMPLATE_OUTPUT_BUCKET} --code-bucket ${DIST_OUTPUT_BUCKET} --solution-name amcufa --version ${VERSION} --region ${REGION} --profile ${PROFILE} | tee >( grep TEMPLATE >template )
~~~~
will result in an error message
> ./deployment/build-s3-dist.sh: line 208: cd: /home/ec2-user/environment/amazon-marketing-cloud-uploader-from-aws/lambda_layer_factory/: No such file or directory

**Expected behavior**
Successful deployment. It is only an incorrect path provided here.

**Please complete the following information about the solution:**
- Version: v1.0.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0222) - amcufa **v1.0.0**. This is the base AWS CloudFormation template that defines resources and nested stacks for this solution._". If the description does not contain the version information, you can look at the mappings section of the template:

- Region: [we tested `eu-west-1` ]

**Screenshots**
n/a

**Additional context**
We used the advanced implementation option in order to test an implementation in AWS region `eu-west-1`.

**Comment by ianwow** [comment]
I think this was user error, which we resolved via chat, so I'm closing this issue. Please reopen if I'm mistaken.
