### ISSUE TITLE
Unit test for Glue

### ISSUE THREAD

**Issue by ikp4success** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#9]
Add a test to the CI/CD pipeline that validates the Glue script.
- 1000 rows of fact data maps to 1000 rows of hashed fact data
  - csv and json
- timeseries partitioning
- hashed columns remain unmodified
- pii columns are hashed
- non pii columns are unmodified
- floats described as integerers are etl'd as floats but schema is set as integer

**Comment by andrewmarriott-aws** [comment]
tests should validate the distinct normalization pattern of any enabled country

**Comment by andrewmarriott-aws** [comment]
Done: https://github.com/aws-solutions/amazon-marketing-cloud-uploader-from-aws/pull/109
